//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL()
        {
            this.Detail_Bill = new HashSet<Detail_Bill>();
        }
    
        public long ID_Bill { get; set; }
        public Nullable<long> TOTAL { get; set; }
        public Nullable<long> ID_EMPLOYEE { get; set; }
        public Nullable<long> ID_CUSTOMER { get; set; }
        public Nullable<long> ID_Voucher { get; set; }
        public Nullable<long> ID_Table { get; set; }
    
        public virtual TABLE TABLE { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Bill> Detail_Bill { get; set; }
    }
}
