//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public long ID { get; set; }
        public Nullable<long> TotalPrice { get; set; }
        public Nullable<long> ID_EMPLOYEE { get; set; }
        public Nullable<long> ID_CUSTOMER { get; set; }
        public Nullable<long> ID_PRODUCT { get; set; }
        public string ID_VOUCHER { get; set; }
        public Nullable<long> ID_TABLES { get; set; }
    
        public virtual TABLE TABLE { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
