//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class CUSTOMER : BaseViewModel
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> POINT_ACCUMULATION { get; set; }
        public Nullable<int> DELETED { get; set; }
    }
}
