//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Bill
    {
        public long ID_Product { get; set; }
        public long ID_Bill { get; set; }
        public Nullable<long> Amount { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual Product Product { get; set; }
    }
}
