//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOOD
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<System.DateTime> ExpriteTime { get; set; }
    }
}
